### ISSUE TITLE
Not compatible with Legacy Mod Menu 1.1.0

### ISSUE THREAD

**Issue by yakisiklibaran32** [YetAnotherMcModder/Legacy-VanillaFix#1]
Game doesnt boot up when launching with legacy vanillafix and legacy mod menu 1.1.0

**Comment by YetAnotherMcModder** [comment]
I forgot to remove the entrypoint for modmenu in *fabric.mod.json* that was causing the issue
I fixed the issue, and will soon reupload v1.0.8 on Modrinth with the fix included
I alredy uploaded the fixed version on Github
