### ISSUE TITLE
1.9.4 support?

### ISSUE THREAD

**Issue by Hu1night** [YetAnotherMcModder/Legacy-VanillaFix#2]

**Comment by YetAnotherMcModder** [comment]
I'm testing it right now, the 1.8 build with 2 mixins disabled almost works, but there's a crash beacuse a method in CrashReport is called that doesn't exist in 1.9.4. It's pretty likely that I will have to make a separate 1.9.x version of this mod.

**Comment by YetAnotherMcModder** [comment]
I've just released the 1.9.4 version here on Github (It might work on all 1.9 mc versions).
The _1.0.9_ version of the mod was released early for 1.9.4 beacuse there are feature(s) I still want to add to 1.8.9 version that I can't to the 1.9.4 version as of now.
